// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import '''
package:firebase_core/firebase_core.dart''' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlLlV0GUUEIqBRAH9vsEN6SoDxwErBmT4',
    appId: '1:919474934025:web:e21534af8f42238edc03d8',
    messagingSenderId: '919474934025',
    projectId: 'advert-334c7',
    authDomain: 'advert-334c7.firebaseapp.com',
    storageBucket: 'advert-334c7.appspot.com',
    measurementId: 'G-7MDS1PZ8WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZv7rp3QTRqWDGm-0zi_PuAy_HSbk8zWc',
    appId: '1:919474934025:android:7a417edc98bcbd39dc03d8',
    messagingSenderId: '919474934025',
    projectId: 'advert-334c7',
    storageBucket: 'advert-334c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNCJQBnkQSoBYIo8xtOKuI1qVYOtbgHgw',
    appId: '1:919474934025:ios:fb99fb8555d10300dc03d8',
    messagingSenderId: '919474934025',
    projectId: 'advert-334c7',
    storageBucket: 'advert-334c7.appspot.com',
    iosClientId:
        '919474934025-rtp6s1botj0err1mqhmu9tcgjd2f5tgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.advert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNCJQBnkQSoBYIo8xtOKuI1qVYOtbgHgw',
    appId: '1:919474934025:ios:daa928f1f2a30930dc03d8',
    messagingSenderId: '919474934025',
    projectId: 'advert-334c7',
    storageBucket: 'advert-334c7.appspot.com',
    iosClientId:
        '919474934025-jf1g062jblrm02qtqg40o1emdleh1n9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.advert.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlLlV0GUUEIqBRAH9vsEN6SoDxwErBmT4',
    appId: '1:919474934025:web:d55bc02f04738350dc03d8',
    messagingSenderId: '919474934025',
    projectId: 'advert-334c7',
    authDomain: 'advert-334c7.firebaseapp.com',
    storageBucket: 'advert-334c7.appspot.com',
    measurementId: 'G-78X2TV0M7S',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAlLlV0GUUEIqBRAH9vsEN6SoDxwErBmT4',
    appId: '1:919474934025:web:78d0bb7ce355ec60dc03d8',
    messagingSenderId: '919474934025',
    projectId: 'advert-334c7',
    authDomain: 'advert-334c7.firebaseapp.com',
    storageBucket: 'advert-334c7.appspot.com',
    measurementId: 'G-QHRWREZBP3',
  );
}
